CREATE TABLE group_resources (
    id BIGINT NOT NULL AUTO_INCREMENT,
    group_id BIGINT NOT NULL,
    task_id BIGINT NULL,
    created_by_member_id BIGINT NOT NULL,
    resource_type ENUM('LINK', 'FILE') NOT NULL,
    title VARCHAR(120) NOT NULL,
    external_url VARCHAR(1000) NULL,
    storage_key VARCHAR(500) NULL,
    original_filename VARCHAR(255) NULL,
    content_type VARCHAR(120) NULL,
    size_bytes BIGINT NULL,
    checksum_sha256 CHAR(64) NULL,
    created_at DATETIME(6) NOT NULL,
    deleted_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    INDEX idx_group_resources_group_created (group_id, created_at, id),
    INDEX idx_group_resources_task_created (task_id, created_at, id),
    INDEX idx_group_resources_checksum (group_id, checksum_sha256),
    CONSTRAINT fk_group_resources_group FOREIGN KEY (group_id) REFERENCES work_groups (id),
    CONSTRAINT fk_group_resources_task FOREIGN KEY (task_id) REFERENCES tasks (id),
    CONSTRAINT fk_group_resources_member FOREIGN KEY (created_by_member_id) REFERENCES group_members (id)
) ENGINE = InnoDB;

CREATE TABLE group_subscriptions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    group_id BIGINT NOT NULL,
    subscriber_user_id BIGINT NOT NULL,
    payment_method_id BIGINT NULL,
    plan_code VARCHAR(40) NOT NULL,
    status ENUM('FREE', 'TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCEL_AT_PERIOD_END', 'CANCELLED') NOT NULL,
    amount BIGINT NOT NULL,
    currency CHAR(3) NOT NULL,
    conversion_choice ENUM('UNDECIDED', 'KEEP_FREE', 'CONTINUE_PAID') NOT NULL,
    rollout_notice_at DATETIME(6) NULL,
    decision_deadline DATETIME(6) NULL,
    current_period_start DATETIME(6) NULL,
    current_period_end DATETIME(6) NULL,
    next_billing_at DATETIME(6) NULL,
    cancelled_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_group_subscriptions_group UNIQUE (group_id),
    INDEX idx_group_subscriptions_billing (status, next_billing_at),
    CONSTRAINT fk_group_subscriptions_group FOREIGN KEY (group_id) REFERENCES work_groups (id),
    CONSTRAINT fk_group_subscriptions_user FOREIGN KEY (subscriber_user_id) REFERENCES users (id),
    CONSTRAINT fk_group_subscriptions_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_methods (id)
) ENGINE = InnoDB;

CREATE TABLE report_schedules (
    id BIGINT NOT NULL AUTO_INCREMENT,
    group_id BIGINT NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    recipient_email VARCHAR(255) NOT NULL,
    weekly_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    weekly_day ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY') NULL,
    monthly_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    monthly_day TINYINT NULL,
    language ENUM('KO', 'EN', 'BOTH') NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_report_schedules_group UNIQUE (group_id),
    INDEX idx_report_schedules_active (active, weekly_enabled, monthly_enabled),
    CONSTRAINT fk_report_schedules_group FOREIGN KEY (group_id) REFERENCES work_groups (id),
    CONSTRAINT fk_report_schedules_user FOREIGN KEY (recipient_user_id) REFERENCES users (id)
) ENGINE = InnoDB;

CREATE TABLE report_deliveries (
    id BIGINT NOT NULL AUTO_INCREMENT,
    schedule_id BIGINT NOT NULL,
    period_type ENUM('WEEKLY', 'MONTHLY') NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    language ENUM('KO', 'EN') NOT NULL,
    event_key VARCHAR(160) NOT NULL,
    status ENUM('PENDING', 'SENT', 'FAILED') NOT NULL,
    error_code VARCHAR(100) NULL,
    created_at DATETIME(6) NOT NULL,
    sent_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_report_deliveries_event UNIQUE (event_key),
    INDEX idx_report_deliveries_status_created (status, created_at),
    CONSTRAINT fk_report_deliveries_schedule FOREIGN KEY (schedule_id) REFERENCES report_schedules (id)
) ENGINE = InnoDB;
